(require 'haskell)
(require 'haskell-mode)
(require 'haskell-indentation)
(add-hook 'haskell-mode-hook 'whitespace-mode)
(add-hook 'haskell-mode-hook 'haskell-indentation-mode)
(add-hook 'haskell-mode-hook 'interactive-haskell-mode)
(require 'magit)
(require 'helm-config)
(require 'helm-projectile)
